aviasales/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("flights.urls"), name="flights"),
]

flights/urls.py
from django.urls import path

from .views import FlightsListView, FlightDetailView, SeatPurchaseView, OrderSuccessView, OrderReturnView, OrdersListView


urlpatterns = [
    path("", FlightsListView.as_view(), name="flights-list"),
    path("flight/<int:pk>", FlightDetailView.as_view(), name="flight-detail"),
    path("seat-purchase", SeatPurchaseView.as_view(), name="seat-purchase"),
    path("order-success", OrderSuccessView.as_view(), name="order-success"),
    path("order-return", OrderReturnView.as_view(), name="order-return"),
    path("orders", OrdersListView.as_view(), name="orders-list"),
]

flights/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils import timezone

from datetime import date

from .constants import GenderConstants, FlightClassConstants


class Flight(models.Model):
    airline = models.ForeignKey(
        "Airline",
        on_delete=models.CASCADE,
        related_name="flights",
        verbose_name="Авиакомпания",
    )
    departure_city = models.ForeignKey(
        "City",
        on_delete=models.CASCADE,
        related_name="departure_flights",
        verbose_name="Город вылета",
    )
    landing_city = models.ForeignKey(
        "City",
        on_delete=models.CASCADE,
        related_name="landing_flights",
        verbose_name="Город посадки",
    )
    departure_date = models.DateTimeField(verbose_name="Дата и время вылета")
    landing_date = models.DateTimeField(verbose_name="Дата и время посадки")
    flight_class = models.PositiveIntegerField(
        choices=FlightClassConstants.CHOICES,
        default=FlightClassConstants.ECONOMY,
        verbose_name="Класс",
    )
    price_per_seat = models.FloatField(verbose_name="Цена за место (в долларах)")
    price_per_seat_underage = models.FloatField(
        verbose_name="Цена за десткое место (в долларах)", blank=True, null=True
    )

    class Meta:
        verbose_name = "Рейс"
        verbose_name_plural = "Рейсы"

    def clean(self):
        if self.departure_date < self.landing_date:
            raise ValidationError(
                {"departure_date": f"Дата вылета неможет быть позже даты прилёта."})

    def __str__(self):
        return f"{self.airline}: {self.departure_city}-{self.landing_city} #{self.pk}"

    def free_seats(self):
        return self.seats.count()


class Airline(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название")

    class Meta:
        verbose_name = "Авиакомпания"
        verbose_name_plural = "Авиакомпании"

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название")
    country = models.ForeignKey(
        "Country",
        on_delete=models.CASCADE,
        related_name="cities",
        verbose_name="Страна",
    )

    class Meta:
        verbose_name = "Город"
        verbose_name_plural = "Города"

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название")

    class Meta:
        verbose_name = "Страна"
        verbose_name_plural = "Страны"

    def __str__(self):
        return self.name


class Seat(models.Model):
    flight = models.ForeignKey(
        "Flight", on_delete=models.CASCADE, related_name="seats", verbose_name="Рейс"
    )
    number = models.CharField(max_length=100, verbose_name="Номер")
    is_bought = models.BooleanField(default=False, verbose_name="Куплено")

    class Meta:
        verbose_name = "Место"
        verbose_name_plural = "Места"

    def __str__(self):
        return f"{self.flight}: {self.number}"


class Order(models.Model):
    seat = models.OneToOneField(
        "Seat", on_delete=models.CASCADE, related_name="order", verbose_name="Место"
    )
    email = models.EmailField(verbose_name="Электронная почта")
    phonenumber = models.CharField(max_length=30, verbose_name="Номер телефона")
    contact_face = models.CharField(max_length=100, verbose_name="Контактное лицо")
    created_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата и время создания"
    )

    first_name = models.CharField(max_length=100, verbose_name="Имя", default="")
    last_name = models.CharField(max_length=100, verbose_name="Фамилия", default="")
    patronymic = models.CharField(max_length=100, verbose_name="Отчество", default="")
    gender = models.IntegerField(
        choices=GenderConstants.CHOICES,
        default=GenderConstants.UNKNOWN,
        verbose_name="Пол",
    )
    date_of_birth = models.DateField(verbose_name="Дата рождения", default=timezone.now)
    citizenship_country = models.ForeignKey(
        "Country",
        on_delete=models.CASCADE,
        related_name="passangers",
        verbose_name="Страна гражданства",
        null=True,
    )
    document = models.CharField(max_length=100, verbose_name="Документ", default="")
    document_id = models.CharField(max_length=100, verbose_name="Номер документа", default="")
    total_price = models.FloatField(verbose_name="Итоговая Цена", null=True, blank=True)
    is_active = models.BooleanField(default=True, verbose_name="Актуален")

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        return f"Заказ #{self.pk}"
    
    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        if self.seat.flight.departure_date < timezone.now():
            raise ValidationError(
                {"email": f"Рейс уже неактуален."})

        super().save(force_insert, force_update, *args, **kwargs)

    def flight_name(self):
        return self.seat.flight

    flight_name.short_description = "Рейс"

flights/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import DetailView, FormView
from django import forms
from django.urls import reverse
from django.db.models import Count, Sum

from datetime import datetime
from datetime import date

from .models import Flight, City, Order, Seat


class FlightsListView(TemplateView):

    template_name = "flights_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        flights_list = Flight.objects.all()

        airline = self.request.GET.get("airline")
        if airline:
            flights_list = flights_list.filter(airline=airline)

        departure_date = self.request.GET.get("departure_date")
        if departure_date:
            flights_list = flights_list.filter(departure_date__date=departure_date)

        landing_date = self.request.GET.get("landing_date")
        if landing_date:
            flights_list = flights_list.filter(landing_date__date=landing_date)

        departure_city = self.request.GET.get("departure_city")
        if departure_city:
            flights_list = flights_list.filter(departure_city=departure_city)

        landing_city = self.request.GET.get("landing_city")
        if landing_city:
            flights_list = flights_list.filter(landing_city=landing_city)

        context["flights_list"] = flights_list
        context["cities"] = City.objects.all()

        return context


class FlightDetailView(DetailView):
    model = Flight

    template_name = "flight_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["flight"] = self.object

        return context


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            "email",
            "phonenumber",
            "contact_face",
            "first_name",
            "last_name",
            "patronymic",
            "gender",
            "date_of_birth",
            "citizenship_country",
            "document",
            "document_id",
        ]
    
    def clean_date_of_birth(self):
        date_of_birth = self.cleaned_data['date_of_birth']
        if date_of_birth > date.today():
            raise forms.ValidationError("Дата рождения не может быть в будущем!")
        return date_of_birth


class SeatPurchaseView(FormView):
    model = Order
    form_class = OrderForm

    template_name = "seat_purchase.html"

    def get_success_url(self):        
        seat = Seat.objects.get(id=self.request.GET.get("seat"))                   
        return reverse('flight-detail', kwargs={'pk' : seat.flight.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            seat = Seat.objects.get(id=self.request.GET.get("seat"), is_bought=False)
            context["seat"] = seat
        except Seat.DoesNotExist:
            context["fail_message"] = "Указанное вами сиденье уже занято или его не сущетсвует."

        return context

    def form_valid(self, form):
        today = date.today()
        age = today.year - form.instance.date_of_birth.year - ((today.month, today.day) < (form.instance.date_of_birth.month, form.instance.date_of_birth.day))
        seat = Seat.objects.get(id=self.request.GET.get("seat"))
        if age < 18:
            form.instance.total_price = seat.flight.price_per_seat_underage
        else:
            form.instance.total_price = seat.flight.price_per_seat

        form.instance.seat = seat
        form.instance.save()
        seat.is_bought = True
        seat.save()
        return super().form_valid(form)


class OrderSuccessView(TemplateView):

    template_name = "order_success.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            order = Order.objects.get(pk=self.request.GET.get("order"))
            context["order"] = order
        except Order.DoesNotExist:
            context["fail_message"] = "Указанный вами заказ не существует."

        return context


class OrderReturnView(TemplateView):

    template_name = "order_return.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            order = Order.objects.get(pk=self.request.GET.get("order"), is_active=True)
            seat = order.seat
            seat.is_bought = False
            seat.save()
            order.is_active = False
            order.save()
            context["order"] = order
        except Order.DoesNotExist:
            context["fail_message"] = "Указанного вами билета не существует или он уже возвращён."

        return context



class OrdersListView(TemplateView):

    template_name = "orders_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        orders_list = Order.objects.all()

        starts_at = self.request.GET.get("starts_at")
        if starts_at:
            orders_list = orders_list.filter(created_at__date__gte=starts_at)

        ends_at = self.request.GET.get("ends_at")
        if ends_at:
            orders_list = orders_list.filter(created_at__date__lte=ends_at)

        context["orders_list"] = orders_list
        orders_list = orders_list.filter(is_active=True).aggregate(total_sum=Sum("total_price"))
        context["orders_sum"] = orders_list.get("total_sum")

        return context

flights/templates/flight_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Рейс #{{ flight.pk }}</title>
    {{ request.comment|safe }}
</head>
<body style="font-family: Arial; font-size: 18px">
    {% comment %} <header style="background-color: black; color: white; display: block; height: 40px; font-weight: 800">
        <ul style = "list-style-type: none; padding-top: 6px;">
            {% for item in nav_bar %}
            <li style="display: inline; margin: 0 20px;"> <a href="{{item.link}}" style="text-decoration: none; color:inherit">{{item.name}}</a></li>
            {% endfor %}
        </ul>
    </header> {% endcomment %}

    <h1>Рейс #{{ flight.pk }}</h1>
    <ul class="flights_list">
        <li class="flights_list__item"> 
            <a style="text-decoration: none;">
                <div>Авиакомпания: {{ flight.airline }}</div>
                <div>{{ flight.get_flight_class_display }}</div>
                <div>Город вылета: {{flight.departure_city}}</div>
                <div>Дата и время вылета: {{flight.departure_date}}</div>
                <div>Город посадки: {{flight.landing_city}}</div>
                <div>Дата и время посадки: {{flight.landing_date}}</div>
                <div>Оставшихся мест: {{ flight.free_seats }}</div>
                <div>Цена за место: {{ flight.price_per_seat }} $ (для несовершеннолетних : {{ flight.price_per_seat_underage|default_if_none:flight.price_per_seat }} $)</div>
            </a>
        </li>
    </ul>
    <h2>Места: </h2>
    <p>Нажмите на номер, чтобы приобрести место: </p>
    <ul class="seats_list">
        {% for seat in flight.seats.all %}
        <li class="seats_list__item{% if seat.is_bought %} bought{% endif %}">
            <a style="text-decoration: none;" {% if not seat.is_bought %} href="{% url 'seat-purchase' %}?seat={{ seat.pk }}"{% endif %}>
            {{ seat.number }}
            <a>
        </li>
        {% endfor %}
    </ul>
</body>
<style>
    .flights_list {
        list-style-type: none;
    }

    .flights_list__item {
        margin-bottom: 10px;
        border: black solid 1px;
        width: fit-content;
        padding: 20px;
        padding-right: 200px;
    }

    .seats_list {
    }

    .seats_list__item {
        display: inline-block;
        margin-right: 10px;
    }

    .seats_list__item a {
        color: black;
    }

    .seats_list__item.bought {
        color: grey !important;
        text-decoration: line-through;
    }

    .seats_list__item.bought a {
        color: grey !important;
    }
</style>
</html>

flights/templates/flights_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Рейсы</title>
    {{ request.comment|safe }}
</head>
<body style="font-family: Arial; font-size: 18px">
    <h1>Рейсы</h1>
    <form action="" method="get" id="filter_form">
        <label>Вылет: </label>
        <select name="departure_city" id="city_field">
            <option value="">Любой</option> 
            {% for city in cities %}
            <option value="{{ city.pk }}"{% if request.GET.departure_city|floatformat:"0" == city.pk|floatformat:"0" %} selected{% endif %}>{{ city.name }}</option>
            {% endfor %}
        </select>
        <input type="date" name="departure_date" value="{{ request.GET.departure_date }}" id="date_field">
        <label>Посадка: </label>
        <select name="landing_city" id="city_field_2">
            <option value="">Любой</option> 
            {% for city in cities %}
            <option value="{{ city.pk }}"{% if request.GET.landing_city|floatformat:"0" == city.pk|floatformat:"0" %} selected{% endif %}>{{ city.name }}</option>
            {% endfor %}
        </select>
        <input type="date" name="landing_date" value="{{ request.GET.landing_date }}" id="date_field_2">
        <button id="submit">Отфильтровать</button>
        <button onclick="event.preventDefault(); document.querySelector('#date_field').value=null; document.querySelector('#date_field_2').value=null; document.querySelector('#city_field').value=''; document.querySelector('#city_field_2').value=''">Сбросить фильтры</button>
    </form>
    <ul class="flights_list">
        {% for flight in flights_list %}
        <li class="flights_list__item"> 
            <a style="text-decoration: none; color: black;" href="{% url 'flight-detail' pk=flight.pk %}">
                <div>Авиакомпания: {{flight.airline}}</div>
                <div>{{ flight.get_flight_class_display }}</div>
                <div>Город вылета: {{flight.departure_city}}</div>
                <div>Дата и время вылета: {{flight.departure_date}}</div>
                <div>Город посадки: {{flight.landing_city}}</div>
                <div>Дата и время посадки: {{flight.landing_date}}</div>
                <div>Оставшихся мест: {{ flight.free_seats }}</div>
                <div>Цена за место: {{ flight.price_per_seat }} $ (для несовершеннолетних : {{ flight.price_per_seat_underage|default_if_none:flight.price_per_seat }} $)</div>
            </a>
        </li>
        {% endfor %}
    </ul>
</body>
<style>
    .flights_list {
        list-style-type: none;
    }

    .flights_list__item {
        margin-bottom: 10px;
        border: black solid 1px;
        width: fit-content;
        padding: 20px;
        padding-right: 200px;
    }
</style>
</html>

flights/templates/order_return.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Возврат билета</title>
    {{ request.comment|safe }}
</head>
<body style="font-family: Arial; font-size: 18px">
    {% if not fail_message %}
    <h1>Возврат билета #{{ order.pk }} был успешен!</h1>
    {% else %}
    <h1>{{ fail_message }}</h1>
    {% endif %}
</body>
</html>

flights/templates/order_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Спасибо за покупку!</title>
    {{ request.comment|safe }}
</head>
<body style="font-family: Arial; font-size: 18px">
    <h1>Спасибо за покупку!</h1>
    <p>{{ order }}</p>
    <p>{{ order.seat }}</p>
    <p>Введите номер заказа на странице возврата, чтобы вернуть билет, или перейдите по ссылке ниже.</p>
    <a href="{% url 'order-return' %}?order={{ order.pk }}">ВЕРНУТЬ БИЛЕТ</a>
</body>
</html>

flights/templates/orders_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Заказы</title>
    {{ request.comment|safe }}
</head>
<body style="font-family: Arial; font-size: 18px">
    <h1>Заказы</h1>
    <form action="" method="get" id="filter_form">
        <label>С: </label>
        <input type="date" name="starts_at" value="{{ request.GET.starts_at }}" id="date_field">
        <label>По: </label>
        <input type="date" name="ends_at" value="{{ request.GET.ends_at }}" id="date_field_2">
        <button id="submit">Отфильтровать</button>
        <button onclick="event.preventDefault(); document.querySelector('#date_field').value=null; document.querySelector('#date_field_2').value=null;">Сбросить фильтры</button>
    </form>
    <h2>Итоговая выручка: {{ orders_sum|default:"0" }} $</h2>
    <ul class="flights_list">
        {% for order in orders_list %}
        <li class="flights_list__item" {% if not order.is_active %}style="background-color: grey;"{% endif %}> 
            <div>Заказ №{{ order.pk }}</div>
            <div>Итоговая сумма: {{ order.total_price }}$</div>
            <br>
            <div>{% if order.is_active %}Активный{% else %}Возвращён{% endif %}</div>
        </li>
        {% endfor %}
    </ul>
</body>
<style>
    .flights_list {
        list-style-type: none;
    }

    .flights_list__item {
        margin-bottom: 10px;
        border: black solid 1px;
        width: fit-content;
        padding: 20px;
        padding-right: 200px;
    }
</style>
</html>

flights/templates/seat_purchase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Покупка места</title>
    {{ request.comment|safe }}
</head>
<body style="font-family: Arial; font-size: 18px">
    {% if fail_message %}
        <h1>{{ fail_message }}</h1>
    {% else %}
        <h1>Покупка места {{ seat.number }} для Рейса "{{seat.flight}}"</h1>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
            </div>
            {% endfor %}
            <input type="submit">
        </form>
    {% endif %}
</body>
<style>
    .fieldWrapper {
        margin-bottom: 30px;
    }
</style>